### ISSUE TITLE
Request help on running dcm4chee on Jboss7

### ISSUE THREAD

**Issue by Raghava28051984** [dcm4che/dcm4che.github.io#2]
Hi 

We are looking latest dcm4chee setup which will run on jboss7 .Currently we are exploring  dcm4chee-2.18.3-psql which is not working on Jboss7.
It will be better if anyone can provide the installation documentation  also very much appreciated .

**Comment by hczedik** [comment]
Please post your questions only in the official dcm4che google group:
https://groups.google.com/forum/#!forum/dcm4che
